# Generated by Django 5.0.1 on 2024-02-20 17:36

import apps.core.custom_model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_alter_pages_slug_alter_pages_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image1',
            field=apps.core.custom_model_fields.Base64Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=apps.core.custom_model_fields.Base64Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='image1',
            field=apps.core.custom_model_fields.Base64Field(blank=True, help_text='Size: 1920x570', null=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bucket/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bucket/'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bucket/'),
        ),
    ]
