# Generated by Django 5.0.1 on 2024-02-20 17:37

import apps.core.custom_model_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_category_image1_product_image1_slide_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image1',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image1',
        ),
        migrations.AddField(
            model_name='category',
            name='image_new',
            field=models.FileField(blank=True, null=True, upload_to='bucket/'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_new',
            field=models.FileField(blank=True, null=True, upload_to='bucket/'),
        ),
        migrations.AddField(
            model_name='slide',
            name='image_new',
            field=models.FileField(blank=True, null=True, upload_to='bucket/'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=apps.core.custom_model_fields.Base64Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=apps.core.custom_model_fields.Base64Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=apps.core.custom_model_fields.Base64Field(blank=True, help_text='Size: 1920x570', null=True),
        ),
    ]
