# Generated by Django 5.0.1 on 2024-02-20 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_category_image1_remove_product_image1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image_new',
        ),
        migrations.RemoveField(
            model_name='slide',
            name='image_new',
        ),
    ]
