# Generated by Django 5.0.1 on 2024-02-20 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_product_image_new_remove_slide_image_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='image_new',
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bucket/categories'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to='bucket/products'),
        ),
        migrations.AlterField(
            model_name='slide',
            name='image',
            field=models.FileField(blank=True, help_text='Size: 1920x570', null=True, upload_to='bucket/slides'),
        ),
    ]
