# Generated by Django 5.0.1 on 2024-02-29 18:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_remove_product_images_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
