# Generated by Django 5.0.1 on 2024-02-21 16:47

import django_resized.forms
import gdstorage.storage
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_users_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='profile',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='WEBP', keep_meta=True, null=True, quality=75, scale=None, size=[400, 400], storage=gdstorage.storage.GoogleDriveStorage(), upload_to='bucket/profiles'),
        ),
    ]
